/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/agents/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Risk */
        get: operations["agent_risk_v2_agents_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Detail */
        get: operations["agent_detail_v2_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_v2_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/dashboard/action-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Action Breakdown */
        get: operations["dashboard_action_breakdown_v2_dashboard_action_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/dashboard/decision-volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Decision Volume */
        get: operations["dashboard_decision_volume_v2_dashboard_decision_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_v2_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_v2_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/decisions/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decision */
        get: operations["get_decision_v2_decisions__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Action */
        post: operations["evaluate_action_v2_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/integrations/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration Health */
        get: operations["integration_health_v2_integrations_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policies */
        get: operations["policies_v2_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/policies/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Summary */
        get: operations["policy_summary_v2_policies_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/service/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service Status */
        get: operations["service_status_v2_service_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionBreakdown */
        ActionBreakdown: {
            freshness: components["schemas"]["MetricFreshness"];
            /** Items */
            items: components["schemas"]["ActionBreakdownItem"][];
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            window: components["schemas"]["DashboardWindow"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** ActionBreakdownItem */
        ActionBreakdownItem: {
            /** Action Type */
            action_type: string;
            /** Decision Count */
            decision_count: number;
            /** Share Percent */
            share_percent: number;
        };
        /** AgentDecisionReference */
        AgentDecisionReference: {
            /** Action Type */
            action_type: string | null;
            /** Behavioral Score */
            behavioral_score: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ALLOW" | "WOULD-BLOCK" | "BLOCK";
        };
        /** AgentDetail */
        AgentDetail: {
            /** Agent Id */
            agent_id: string;
            /** Allow Count */
            allow_count: number;
            /** Block Count */
            block_count: number;
            /** Decision Count */
            decision_count: number;
            evaluation_latency: components["schemas"]["LatencyMetric"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            freshness: components["schemas"]["MetricFreshness"];
            /** High Risk Count */
            high_risk_count: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Recent Decisions */
            recent_decisions: components["schemas"]["AgentDecisionReference"][];
            /** Risk Score */
            risk_score: number;
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            window: components["schemas"]["DashboardWindow"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /** Would Block Count */
            would_block_count: number;
        };
        /** AgentRiskItem */
        AgentRiskItem: {
            /** Agent Id */
            agent_id: string;
            /** Block Count */
            block_count: number;
            /** Decision Count */
            decision_count: number;
            /** High Risk Count */
            high_risk_count: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Risk Score */
            risk_score: number;
            /** Would Block Count */
            would_block_count: number;
        };
        /** AgentRiskPage */
        AgentRiskPage: {
            freshness: components["schemas"]["MetricFreshness"];
            /** Items */
            items: components["schemas"]["AgentRiskItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            window: components["schemas"]["DashboardWindow"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** AuditContinuity */
        AuditContinuity: {
            /** Digest */
            digest: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Previous Digest */
            previous_digest?: string | null;
            /** Sequence */
            sequence: number;
        };
        /** AuditEventPage */
        AuditEventPage: {
            /** Items */
            items: components["schemas"]["AuditEventView"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Snapshot Sequence */
            snapshot_sequence: number;
        };
        /** AuditEventView */
        AuditEventView: {
            /**
             * Detail Retention State
             * @enum {string}
             */
            detail_retention_state: "retained" | "redacted" | "not_collected";
            /** Digest */
            digest: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Integrity Metadata */
            integrity_metadata: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Previous Digest */
            previous_digest?: string | null;
            /** Sequence */
            sequence: number;
            /** Signature Present */
            signature_present: boolean;
            /** Signing Key Id */
            signing_key_id: string | null;
            /** Trace Id */
            trace_id: string | null;
        };
        /** CanonicalAction */
        CanonicalAction: {
            /** Action Type */
            action_type: string;
            /** Agent Id */
            agent_id: string;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Consequential */
            consequential: boolean;
            /** Target */
            target: string;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Critical */
            critical: boolean;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
        };
        /** DashboardSummary */
        DashboardSummary: {
            active_agents: components["schemas"]["MetricValue"];
            allowed: components["schemas"]["MetricValue"];
            blocked: components["schemas"]["MetricValue"];
            /**
             * Comparison End
             * Format: date-time
             */
            comparison_end: string;
            /**
             * Comparison Start
             * Format: date-time
             */
            comparison_start: string;
            decisions: components["schemas"]["MetricValue"];
            evaluation_latency: components["schemas"]["LatencyMetric"];
            freshness: components["schemas"]["MetricFreshness"];
            high_risk_decisions: components["schemas"]["MetricValue"];
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            window: components["schemas"]["DashboardWindow"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            would_block: components["schemas"]["MetricValue"];
        };
        /**
         * DashboardWindow
         * @enum {string}
         */
        DashboardWindow: "24h" | "7d" | "30d";
        /** DecisionDetail */
        DecisionDetail: {
            action: components["schemas"]["SafeCanonicalAction"] | null;
            /** Action Type */
            action_type: string | null;
            /** Agent Id */
            agent_id: string;
            audit: components["schemas"]["AuditContinuity"];
            /** Behavioral Score */
            behavioral_score: number;
            /** Blast Radius */
            blast_radius: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail Available */
            detail_available: boolean;
            /** Detail Deleted At */
            detail_deleted_at: string | null;
            /** Evidence Degraded */
            evidence_degraded: boolean | null;
            /** Evidence State */
            evidence_state: {
                [key: string]: unknown;
            } | null;
            /** Input Digest */
            input_digest: string;
            /** Mitre Mappings */
            mitre_mappings: {
                [key: string]: unknown;
            }[] | null;
            /** Pipeline Timings */
            pipeline_timings: {
                [key: string]: unknown;
            } | null;
            /**
             * Policy Decision
             * @enum {string}
             */
            policy_decision: "ALLOW" | "DENY" | "REQUIRE_APPROVAL" | "NOT_APPLICABLE";
            /** Policy Matches */
            policy_matches: components["schemas"]["PolicyMatchDetail"][];
            /** Policy Pack Version */
            policy_pack_version: string;
            /** Predicted Next */
            predicted_next: {
                [key: string]: unknown;
            } | null;
            /** Reasons */
            reasons: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Response Status
             * @enum {string}
             */
            response_status: "PENDING" | "DELIVERY_PENDING" | "DELIVERED" | "FAILED" | "EXECUTED";
            /** Similar Decisions */
            similar_decisions: components["schemas"]["SimilarDecisionReference"][];
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ALLOW" | "WOULD-BLOCK" | "BLOCK";
        };
        /** DecisionPage */
        DecisionPage: {
            /** Items */
            items: components["schemas"]["DecisionSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** DecisionSummary */
        DecisionSummary: {
            /** Action Type */
            action_type: string | null;
            /** Agent Id */
            agent_id: string;
            /** Behavioral Score */
            behavioral_score: number;
            /** Blast Radius */
            blast_radius: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail Available */
            detail_available: boolean;
            /** Evidence Degraded */
            evidence_degraded: boolean | null;
            /**
             * Policy Decision
             * @enum {string}
             */
            policy_decision: "ALLOW" | "DENY" | "REQUIRE_APPROVAL" | "NOT_APPLICABLE";
            /**
             * Response Status
             * @enum {string}
             */
            response_status: "PENDING" | "DELIVERY_PENDING" | "DELIVERED" | "FAILED" | "EXECUTED";
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ALLOW" | "WOULD-BLOCK" | "BLOCK";
        };
        /** DecisionVolume */
        DecisionVolume: {
            /**
             * Bucket Granularity
             * @enum {string}
             */
            bucket_granularity: "hour" | "day";
            freshness: components["schemas"]["MetricFreshness"];
            /** Points */
            points: components["schemas"]["DecisionVolumePoint"][];
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            window: components["schemas"]["DashboardWindow"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** DecisionVolumePoint */
        DecisionVolumePoint: {
            /** Allow */
            allow: number;
            /** Block */
            block: number;
            /**
             * Bucket Start
             * Format: date-time
             */
            bucket_start: string;
            /** Total */
            total: number;
            /** Would Block */
            would_block: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvaluationRequest */
        EvaluationRequest: {
            action: components["schemas"]["CanonicalAction"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceEnvelope"][];
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /** Behavioral Score */
            behavioral_score: number;
            /** Blast Radius */
            blast_radius: string;
            /** Evidence Degraded */
            evidence_degraded: boolean;
            /** Matched Rules */
            matched_rules: components["schemas"]["PolicyMatchResponse"][];
            /** Mitre Atlas */
            mitre_atlas: string[];
            /** Mitre Attack */
            mitre_attack: string[];
            pipeline_timings: components["schemas"]["PipelineTimings"];
            /**
             * Policy Decision
             * @enum {string}
             */
            policy_decision: "ALLOW" | "DENY" | "REQUIRE_APPROVAL";
            /** Policy Pack Version */
            policy_pack_version: string;
            /** Predicted Next */
            predicted_next: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Reasons */
            reasons: string[];
            /**
             * Response Status
             * @enum {string}
             */
            response_status: "DECIDED" | "DELIVERY_PENDING";
            /** Similar Decision Ids */
            similar_decision_ids: string[];
            /** Trace Id */
            trace_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ALLOW" | "WOULD-BLOCK" | "BLOCK";
        };
        /** EvidenceEnvelope */
        EvidenceEnvelope: {
            /** Digest */
            digest: string;
            /** Domain */
            domain: string;
            /** Key Id */
            key_id: string;
            /** Nonce */
            nonce: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance: string;
            /** Signature */
            signature: string;
            /** Source Identity */
            source_identity: string;
            /** Tenant Id */
            tenant_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationHealthPage */
        IntegrationHealthPage: {
            /** Items */
            items: components["schemas"]["IntegrationHealthView"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "empty";
        };
        /** IntegrationHealthView */
        IntegrationHealthView: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Diagnostic Code */
            diagnostic_code?: string | null;
            /** Integration Key */
            integration_key: string;
            /** Integration Kind */
            integration_kind: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "HEALTHY" | "DEGRADED" | "UNAVAILABLE" | "UNKNOWN" | "STALE";
        };
        /** LatencyMetric */
        LatencyMetric: {
            /** P95 Ms */
            p95_ms?: number | null;
            /** Sample Count */
            sample_count: number;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "live";
            /** Version */
            version: string;
        };
        /** MetricFreshness */
        MetricFreshness: {
            /**
             * Poll After Seconds
             * @default 30
             */
            poll_after_seconds: number;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            /** Source Last Updated At */
            source_last_updated_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "empty";
        };
        /** MetricValue */
        MetricValue: {
            /** Change Percent */
            change_percent: number | null;
            /** Previous Value */
            previous_value: number;
            /** Value */
            value: number;
        };
        /** PipelineTimings */
        PipelineTimings: {
            /** Audit Ms */
            audit_ms?: number | null;
            /** Baseline Ms */
            baseline_ms?: number | null;
            /** Behavioral Ms */
            behavioral_ms: number;
            /**
             * Normalization Ms
             * @default 0
             */
            normalization_ms: number;
            /** Persistence Ms */
            persistence_ms?: number | null;
            /** Policy Ms */
            policy_ms: number;
            /** Sie Ms */
            sie_ms?: number | null;
            /** Total Ms */
            total_ms: number;
        };
        /** PolicyMatchDetail */
        PolicyMatchDetail: {
            /**
             * Effect
             * @enum {string}
             */
            effect: "ALLOW" | "DENY" | "REQUIRE_APPROVAL";
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
        };
        /** PolicyMatchResponse */
        PolicyMatchResponse: {
            /** Frameworks */
            frameworks: string[];
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Reason */
            reason: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** PolicyPage */
        PolicyPage: {
            /** Items */
            items: components["schemas"]["PolicyRuleView"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Pack Name */
            pack_name: string;
            /** Pack Version */
            pack_version: string;
        };
        /** PolicyRuleView */
        PolicyRuleView: {
            /** Category */
            category: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "ALLOW" | "DENY" | "REQUIRE_APPROVAL";
            /** Frameworks */
            frameworks: string[];
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Prerequisites */
            prerequisites: string[];
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** PolicySummary */
        PolicySummary: {
            /** Counts By Status */
            counts_by_status: {
                [key: string]: number;
            };
            /**
             * Default Decision
             * @enum {string}
             */
            default_decision: "ALLOW" | "DENY" | "REQUIRE_APPROVAL";
            /** Enforced Rules */
            enforced_rules: number;
            /** Pack Name */
            pack_name: string;
            /** Pack Version */
            pack_version: string;
            /** Planned Rules */
            planned_rules: number;
            /** Total Rules */
            total_rules: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
            /** Service */
            service: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Version */
            version: string;
        };
        /** SafeCanonicalAction */
        SafeCanonicalAction: {
            /** Action Type */
            action_type: string;
            /** Agent Id */
            agent_id: string;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Consequential */
            consequential: boolean;
            /** Target */
            target: string;
        };
        /** ServiceComponent */
        ServiceComponent: {
            /** Diagnostic Code */
            diagnostic_code?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Measured At */
            measured_at?: string | null;
            /**
             * Name
             * @enum {string}
             */
            name: "gate" | "postgresql" | "sie" | "outbox" | "audit" | "adapters";
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unavailable" | "unmeasured";
        };
        /** ServiceStatus */
        ServiceStatus: {
            /** Components */
            components: components["schemas"]["ServiceComponent"][];
            /** Instrumented Pipeline Stages */
            instrumented_pipeline_stages: string[];
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unavailable";
        };
        /** SimilarDecisionReference */
        SimilarDecisionReference: {
            /** Action Type */
            action_type: string | null;
            /** Agent Id */
            agent_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ALLOW" | "WOULD-BLOCK" | "BLOCK";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A critical dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    agent_risk_v2_agents_risk_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["DashboardWindow"];
                limit?: number;
                cursor?: string | null;
                minimum_risk_score?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRiskPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    agent_detail_v2_agents__agent_id__get: {
        parameters: {
            query?: {
                window?: components["schemas"]["DashboardWindow"];
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    audit_events_v2_audit_events_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                event_type?: string | null;
                trace_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    dashboard_action_breakdown_v2_dashboard_action_breakdown_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["DashboardWindow"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionBreakdown"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    dashboard_decision_volume_v2_dashboard_decision_volume_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["DashboardWindow"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionVolume"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    dashboard_summary_v2_dashboard_summary_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["DashboardWindow"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_decisions_v2_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                created_from?: string | null;
                created_to?: string | null;
                verdict?: ("ALLOW" | "WOULD-BLOCK" | "BLOCK") | null;
                policy_decision?: ("ALLOW" | "DENY" | "REQUIRE_APPROVAL" | "NOT_APPLICABLE") | null;
                response_status?: ("PENDING" | "DELIVERY_PENDING" | "DELIVERED" | "FAILED" | "EXECUTED") | null;
                evidence_degraded?: boolean | null;
                agent_id?: string | null;
                action_type?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_decision_v2_decisions__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    evaluate_action_v2_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    integration_health_v2_integrations_health_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: ("HEALTHY" | "DEGRADED" | "UNAVAILABLE" | "UNKNOWN") | null;
                integration_kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationHealthPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    policies_v2_policies_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: string | null;
                category?: string | null;
                severity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    policy_summary_v2_policies_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    service_status_v2_service_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
