export const backendSurfaces = [
  {
    surface: "Control plane probes",
    method: "GET",
    path: "/livez, /readyz",
    audience: "Operations",
    evidence: "Measured dependency state",
    boundary: "Production",
  },
  {
    surface: "Control plane evaluation",
    method: "POST",
    path: "/v2/evaluations",
    audience: "Workload",
    evidence: "Persisted decisions and audit",
    boundary: "Production",
  },
  {
    surface: "Control plane reads",
    method: "GET",
    path: "/v2/dashboard, decisions, agents, policies, integrations, audit",
    audience: "Console",
    evidence: "Direct typed API coverage",
    boundary: "Production",
  },
  {
    surface: "Legacy gate",
    method: "POST",
    path: "/v1/gate",
    audience: "Workload",
    evidence: "Frozen compatibility contract",
    boundary: "Legacy",
  },
  {
    surface: "Legacy gate probe",
    method: "GET",
    path: "/health",
    audience: "Operations",
    evidence: "Deployment health probe",
    boundary: "Legacy",
  },
  {
    surface: "Edge authorization",
    method: "POST",
    path: "/v1/actions/evaluate",
    audience: "Workload",
    evidence: "Edge runtime contract",
    boundary: "Production",
  },
  {
    surface: "Durable Object runtime",
    method: "POST",
    path: "/consume, /v1/actions/evaluate",
    audience: "Internal",
    evidence: "Runtime and replay boundary",
    boundary: "Internal",
  },
  {
    surface: "Cloudflare demo",
    method: "GET / POST",
    path: "/healthz, /api/demo-actions, /v1/demo/authorize-and-execute",
    audience: "Demonstration",
    evidence: "Explicit non-production boundary",
    boundary: "Demo",
  },
] as const;
